### ISSUE TITLE
Popped out combat tracker keeps resizing

### ISSUE THREAD

**Issue by Kosyne** [Dorako/pf2e-dorako-ui#118] opened 2022-12-04 03:01 UTC
Combat tracker keeps resizing whenever an update occurs (next turn is clicked, new player added to it, etc).

For what it's worth, I'm using `sidebar-resizer` that allows resizing these windows.

Also, the combat tracker's `min-width` is too large, can't make it as compact as I can with the default theme.

**Comment by Dorako** [comment] 2022-12-28 22:07
I removed the minimum width which solves one of the issues you're having.
I can't reproduce the resizing though, adding combatants and passing the turn doesn't resize anything for me.

**Comment by Kosyne** [comment] 2022-12-29 06:55
Thanks!

For the resizing, it definitely resolves when I remove this package, I'll do some further testing and see if I can't find the exact cause.

For what it's worth, I'm using the pathfinder 2e module, and a few others.

**Comment by Dorako** [comment] 2023-01-14 13:20
I'm closing this issue due to lack of data, feel free to re-open if you can find reproduction steps.

**Closed by Dorako** 2023-01-14 13:20 UTC
