### ISSUE TITLE
Some text way too hard to read.

### ISSUE THREAD

**Issue by LynShimo** [Dorako/pf2e-dorako-ui#227] opened 2023-08-09 17:17 UTC
v11 307, 5.3.1, dorako 2.3.9 and Pathfinder  UI v3 11.307.4

Certain windows and settings make the text too similar to the background making it illegible. Here is an example when trying to set up playlists:
![Screenshot 2023-08-09 103340](https://github.com/Dorako/pf2e-dorako-ui/assets/141860748/1f569c16-fb10-4c5a-8f65-88dd1d4ba96b)

Turning off Dorako's UI fixes this issue so it seems to be an issue of the module or compatibility with other UI modules.

**Comment by Peach774** [comment] 2023-08-11 02:46
I've noticed this with certain windows as well, like this type of inline roll: light vs dark mode
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/5171184/8ca771f2-6df7-46ce-91e2-074c325fca7d)
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/5171184/33a2b884-82cd-43e1-b822-4a546735b7ef)
As well as some stuff like the implement setting window for thaumaturge: light vs dark mode
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/5171184/d3dc5497-3d2a-42b3-b69e-c7f9b838246d)
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/5171184/14d03a72-87f3-435a-bf8e-1bc81b64c096)
Kinda seems like some fonts/windows aren't being changed?

**Comment by Dorako** [comment] 2023-08-11 12:34
It's more like the text _is_ changing, either when it's not supposed to, or in situations where the background should be adjusted.

If you can provide reproduction steps for the issues you see, it's much easier for me to fix.

**Comment by Peach774** [comment] 2023-08-11 23:46
> It's more like the text _is_ changing, either when it's not supposed to, or in situations where the background should be adjusted.
> 
> If you can provide reproduction steps for the issues you see, it's much easier for me to fix.

The lantern text problem is when you add an implement for a thaumaturge - its under the feats section on the character sheet. The skill inline roll is this: 
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/5171184/84484ade-90d7-4b6c-b434-17265025af1a)
its some kind of other inline roll type - not exactly sure.

**Comment by moarx** [comment] 2023-08-18 02:34
Having this issue in the official Sky King's Tomb module journal entries - some buttons (saves, skill prompts, dice rolls) are showing as black text on a dark blue background with Dorako enabled. When it's disabled their text is white which matches the rest of the journal.


![Screenshot 2023-08-18 033342](https://github.com/Dorako/pf2e-dorako-ui/assets/1758237/72546616-31c8-442f-be1b-55435f7e11f3)

**Comment by Araluen124** [comment] 2023-08-30 17:43
I have a similar problem with the dark mode, some text doesn't change like depicted here where the text stays black
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/104476123/7b1b3412-9691-41ee-b428-4b96b5184572)

**Comment by Dorako** [comment] 2023-08-30 19:04
> I have a similar problem with the dark mode, some text doesn't change like depicted here where the text stays black (It is supposed to be "Attaque à mains nues") ![image](https://user-images.githubusercontent.com/104476123/264428207-7b1b3412-9691-41ee-b428-4b96b5184572.png)

This was introduced in system 5.4.1 and should be fixed now

**Comment by Dorako** [comment] 2023-08-30 19:04
> I've noticed this with certain windows as well, like this type of inline roll: light vs dark mode ![image](https://user-images.githubusercontent.com/5171184/259912369-8ca771f2-6df7-46ce-91e2-074c325fca7d.png) ![image](https://user-images.githubusercontent.com/5171184/259912412-33a2b884-82cd-43e1-b822-4a546735b7ef.png) As well as some stuff like the implement setting window for thaumaturge: light vs dark mode ![image](https://user-images.githubusercontent.com/5171184/259912565-d3dc5497-3d2a-42b3-b69e-c7f9b838246d.png) ![image](https://user-images.githubusercontent.com/5171184/259912600-14d03a72-87f3-435a-bf8e-1bc81b64c096.png) Kinda seems like some fonts/windows aren't being changed?

I think the thaum module author has fixed this

**Comment by Dorako** [comment] 2023-08-30 19:05
> @Dorako Having a similar issue in the official Sky King's Tomb module journal entries - some buttons (saves, skill prompts, dice rolls) are showing as black text on a dark blue background with Dorako enabled, default settings. This happens when the only active modules are Dorako and Sky King's Tomb, and the text turns back to white as intended with Dorako disabled.
> 
> Using the latest Dorako version 2.4.0
> 
> ![Screenshot 2023-08-18 033342](https://user-images.githubusercontent.com/1758237/261484818-72546616-31c8-442f-be1b-55435f7e11f3.jpg)

This one is hard for me to debug, because I don't have access to the module. One day I'll have to coordinate with somebody

**Comment by moarx** [comment] 2023-08-30 20:02
> > @Dorako Having a similar issue in the official Sky King's Tomb module journal entries - some buttons (saves, skill prompts, dice rolls) are showing as black text on a dark blue background with Dorako enabled, default settings. This happens when the only active modules are Dorako and Sky King's Tomb, and the text turns back to white as intended with Dorako disabled.
> > Using the latest Dorako version 2.4.0
> > ![Screenshot 2023-08-18 033342](https://user-images.githubusercontent.com/1758237/261484818-72546616-31c8-442f-be1b-55435f7e11f3.jpg)
> 
> This one is hard for me to debug, because I don't have access to the module. One day I'll have to coordinate with somebody

Well whatever you or Paizo have done in recent updates seems to have fixed it, module access or not! 
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/1758237/ee822ad6-08a6-4500-82b5-1b3ac9e7e754)

**Comment by Dorako** [comment] 2023-08-30 20:03
> > > @Dorako Having a similar issue in the official Sky King's Tomb module journal entries - some buttons (saves, skill prompts, dice rolls) are showing as black text on a dark blue background with Dorako enabled, default settings. This happens when the only active modules are Dorako and Sky King's Tomb, and the text turns back to white as intended with Dorako disabled.
> > > Using the latest Dorako version 2.4.0
> > > ![Screenshot 2023-08-18 033342](https://user-images.githubusercontent.com/1758237/261484818-72546616-31c8-442f-be1b-55435f7e11f3.jpg)
> > 
> > 
> > This one is hard for me to debug, because I don't have access to the module. One day I'll have to coordinate with somebody
> 
> Well whatever you or Paizo have done in recent updates seems to have fixed it, module access or not! ![image](https://user-images.githubusercontent.com/1758237/264459671-ee822ad6-08a6-4500-82b5-1b3ac9e7e754.png) Thanks

oh neat, I did put out a potential fix a few patches ago, but I have no way to verify it.

**Comment by Yuven91** [comment] 2023-09-28 13:42
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/22319152/91a02bb5-4a62-4e91-9617-423cc4b3cd17)
from the new kingmaker module with dorako ui dark theme.
i had a bug where it was like this in light mode too, but i cant replicate

**Comment by Dorako** [comment] 2023-09-28 17:32
> ![image](https://user-images.githubusercontent.com/22319152/271303939-91a02bb5-4a62-4e91-9617-423cc4b3cd17.png) from the new kingmaker module with dorako ui dark theme. i had a bug where it was like this in light mode too, but i cant replicate

Can you check whether this is fixed now?

**Comment by Yuven91** [comment] 2023-09-29 08:41
> > ![image](https://user-images.githubusercontent.com/22319152/271303939-91a02bb5-4a62-4e91-9617-423cc4b3cd17.png) from the new kingmaker module with dorako ui dark theme. i had a bug where it was like this in light mode too, but i cant replicate
> 
> Can you check whether this is fixed in newest update?

looks good now

**Comment by Yuven91** [comment] 2023-09-30 16:28
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/22319152/39597783-05e3-482d-9a94-17cca5e62d1a)
from Abomination Vaults journal

**Comment by Dorako** [comment] 2023-09-30 16:33
@Yuven91 
![CleanShot 2023-09-30 at 18 32 38@2x](https://github.com/Dorako/pf2e-dorako-ui/assets/1561190/3e4bd349-16b8-4fc0-945f-f5fa3c21e3bb)
I don't see this, are you sure you are using the newest version?

**Comment by Yuven91** [comment] 2023-09-30 18:13
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/22319152/e372ec45-edf9-472b-a148-ac93b8ba5457)
ah, you are right. this instance of foundry has an older version

**Closed** 2023-11-01 19:54 UTC
Labels: dark theme legibility
