### ISSUE TITLE
Incompatibility with Cautious Gamemaster's Pack

### ISSUE THREAD

**Issue by MrVauxs** [Dorako/pf2e-dorako-ui#11] opened 2022-02-05 20:47 UTC
Having both CGP and Dorako UI enabled gives the chat a scrollbar leading to nothing, presumably where CGP has it's "X user is typing" pop-up.
![chrome_PRcHtDAjvX](https://user-images.githubusercontent.com/32039708/152658411-95d2bebe-3212-4ee2-b6f6-02e09ffc3424.gif)

**Comment by Dorako** [comment] 2022-02-07 23:55
I can't reproduce this, so maybe it has fixed itself. Please comment here if you can reproduce in the next release

**Comment by MrVauxs** [comment] 2022-02-08 11:31
Note that you need to enable the following setting to see the bug:
![image](https://user-images.githubusercontent.com/32039708/152978790-b1fec568-856a-4087-b89b-c6feb55c7967.png)

**Comment by Dorako** [comment] 2022-02-09 21:34
Maybe fixed in next release?
Please re-open if it looks odd.

**Closed by Dorako** 2022-02-09 21:34 UTC
Labels: bug
