### ISSUE TITLE
PF2E Dorako Making Background of opened compendiums for Savage Pathfinder disappear.

### ISSUE THREAD

**Issue by Deadlander** [Dorako/pf2e-dorako-ui#211] opened 2023-07-16 04:23 UTC
The Dorako UI is changing the background for the Savage Pathfinder Compendiums to semi-transparent black when they are opened. No error in the Console. Here is a picture.
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/13036735/07bdb216-878d-4ee3-8b19-cde0be1ab9dc)

**Comment by Dorako** [comment] 2023-07-16 07:37
Duplicate of https://github.com/Dorako/pf2e-dorako-ui/issues/207
Should be fixed in 2.2.5, let me know if it isn't.

**Closed by Dorako** 2023-07-16 07:37 UTC
