### ISSUE TITLE
Drop Down not Legible in Dark Mode

### ISSUE THREAD

**Issue by Jonoth777** [Dorako/pf2e-dorako-ui#323] opened 2024-07-04 15:02 UTC
Foundry V12.328
PF2 V6.0.4
Version 126.0.6478.127 (Official Build) (64-bit) - Latest at time of writing

Drop Down not Legible in Dark Mode - tried all dark themes, no custom CSS (as far as I know). Issue not present in v11 version of same world.

See Image:
![image](https://github.com/Dorako/pf2e-dorako-ui/assets/56931432/292c09ff-55f8-4375-a168-6bf97ba122af)

**Comment by SoilentBrad** [comment] 2024-07-05 06:20
I was just going to report this. I thought it might have been because I was testing out a temporary node version of v12 until all of my modules are ready, but it looks like other folks are getting it.

**Comment by Dorako** [comment] 2024-07-05 13:37
Yeah it's a recent regression, I hope to fix it this weekend. Dropdowns are notoriously annoying for me to detect and fix, since my development machine uses OS style dropdowns rather than browser-specific ones.

**Comment by Dorako** [comment] 2024-07-06 23:39
Should be fixed now.

**Closed by Dorako** 2024-07-06 23:39 UTC
