### ISSUE TITLE
NPC Sheet Dark Mode

### ISSUE THREAD

**Issue by HongBo-contact** [Dorako/pf2e-dorako-ui#164] opened 2023-02-28 17:12 UTC
Currently the dark mode on NPC sheets makes action description nigh-unreadable due to lack of contrast.

![image](https://user-images.githubusercontent.com/66981178/221926732-9d47335a-4c95-4afd-91e1-995a7619ace4.png)

**Comment by Dorako** [comment] 2023-03-01 19:23
Hi, where are you seeing this?
On the latest version of the system and module I am seeing this:
<img width="682" alt="CleanShot 2023-03-01 at 20 23 23@2x" src="https://user-images.githubusercontent.com/1561190/222243221-9c6d5e95-b77b-4dba-95a3-ca19629f6b05.png">

**Comment by HongBo-contact** [comment] 2023-03-01 19:46
Currently on latest versions of pf2e and ui, my second assumption is that it some sort of compat issue with [this](https://github.com/shemetz/pf2e-see-simple-scale-statistics) module, since it also affects NPC sheets.

**Comment by HongBo-contact** [comment] 2023-03-01 19:49
Update: Formatting issue on the text, sorry.

**Comment by Dorako** [comment] 2023-03-02 09:43
<img width="742" alt="CleanShot 2023-03-02 at 10 41 49@2x" src="https://user-images.githubusercontent.com/1561190/222391305-6da7be1f-c81c-4893-bab6-41838df3aa25.png">
I don't see an issue with SSSS enabled - you could try using the Find the Culprit module to single out whether any specific combination of modules is causing the issue.

**Comment by Dorako** [comment] 2023-03-05 22:23
I'm closing this issue since I can't reproduce it, feel free to re-open if you figure it out

**Closed by Dorako** 2023-03-05 22:23 UTC
