### ISSUE TITLE
Chat "Jump to Bottom" button gets stuck over Chat entry area

### ISSUE THREAD

**Issue by biggusbeardus** [Dorako/pf2e-dorako-ui#231] opened 2023-08-28 22:01 UTC
Hello!

When you clear the chat history the Jump to Bottom button appears over the chat text entry area and doesn't go away. You can clear the chat history again and the button goes away. Otherwise you have to refresh the browser.

![chrome_PBZm4DVx4l](https://github.com/Dorako/pf2e-dorako-ui/assets/42783879/1a08b288-448b-464d-a640-53aef609d6cf)

**Comment by Dorako** [comment] 2023-08-28 22:30
I can't reproduce this in my own testing (button disappears when chat is cleared), but the button is a core foundry thing, I'm just making it yellow.

**Comment by biggusbeardus** [comment] 2023-08-29 12:42
Odd. When. I ran FTC SOMETIMES. A "jump to bottom" button appeared, but
none appeared when your UI was off.

Thanks for looking into it. I can just clear the chat immediately after it
gets stuck and it goes away.

**Comment by Dorako** [comment] 2023-08-30 19:03
This does appear to be an issue, I've seen it on a local install as well

**Comment by KyloBren** [comment] 2023-09-01 17:35
I'm having the same bug, on Foundry v11.308, module version 2.6.2

**Comment by Dorako** [comment] 2023-09-02 16:34
Should be fixed in 2.6.3, let me know if it isn't.

**Comment by Dorako** [comment] 2023-09-03 20:11
I'm closing this, feel free to re-open if it still happens, or this solution has unexpected consequences.

**Closed by Dorako** 2023-09-03 20:11 UTC
Labels: dorako-ui bug, help wanted
