### ISSUE TITLE
Issue: token avatars appear upside down in the chat box when the token is mirrored on the canvas.

### ISSUE THREAD

**Issue by AmerWF** [Dorako/pf2e-dorako-ui#84] opened 2022-10-11 11:12 UTC
I have loaded a blank new world and loaded only Dorako UI to test this. When the token is mirrored on the canvas horizontally, and a roll was made, the new chat card shows that token upside down. It does not happen when I chose the option 'prefer actor image', but it might be an issue for actors which have token arts different to their actor art. 

To replicate, this is what I did:
1. Load a new world with only Dorako UI active. 
2. Create an actor. 
3. Mirror the actor horizontally. 
4. Roll on that actor. 

Thank you.

**Comment by Dorako** [comment] 2022-10-11 20:04
Excellent, somebody posted a picture of this happening for some messages, but didn't know why. Knowing that it might related to mirrored tokens will be a great help

**Comment by criticalham** [comment] 2023-01-13 23:54
I can confirm that this is happening when tokens are flipped as well. The issue seems to be that Dorako UI is applying a `transform: scale(-1)` directly to the avatar div. That `scale(-1)` is equivalent to `scale(-1,-1)`, which is flipping the icon on the x and y axes. I guess it should probebly be flipping on either the x or the y based on how the original actor is flipped (or both if flipped on both axes), via either `scale(-1,1)` or `scale(1,-1)` respectively, but honestly it's probably simpler and better to not imitate the flipping at all.

For now, I've worked around this in my own game by adding the following to my Custom CSS module's global script:
`.portrait-wrapper .avatar.portrait { transform: scale(1) !important; }`

**Comment by Dorako** [comment] 2023-01-14 13:18
Should be fixed in newest release, I just went the easy route of math.abs'ing the scale - this means that mirrored tokens have the exact same avatars as non-mirrored tokens.

**Closed by Dorako** 2023-01-14 13:18 UTC
Labels: bug
